// Jeebs Rapid Application Development
// Copyright (c) bcg|design - licensed under https://mit.bcgdesign.com/2013

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "RCS1224:Make method an extension method.", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.OptionExtensions.DoAuditSwitchAsync``1(System.Threading.Tasks.Task{Jeebs.Option{``0}},System.Func{``0,System.Threading.Tasks.Task},System.Func{Jeebs.IMsg,System.Threading.Tasks.Task})~System.Threading.Tasks.Task{Jeebs.Option{``0}}")]
[assembly: SuppressMessage("Design", "RCS1224:Make method an extension method.", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.OptionExtensions.DoAuditAsync``1(System.Threading.Tasks.Task{Jeebs.Option{``0}},System.Func{Jeebs.Option{``0},System.Threading.Tasks.Task})~System.Threading.Tasks.Task{Jeebs.Option{``0}}")]
[assembly: SuppressMessage("Design", "RCS1224:Make method an extension method.", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.OptionExtensions.DoBindAsync``2(System.Threading.Tasks.Task{Jeebs.Option{``0}},System.Func{``0,System.Threading.Tasks.Task{Jeebs.Option{``1}}},Jeebs.Option.Handler)~System.Threading.Tasks.Task{Jeebs.Option{``1}}")]
[assembly: SuppressMessage("Design", "RCS1224:Make method an extension method.", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.OptionExtensions.DoMapAsync``2(System.Threading.Tasks.Task{Jeebs.Option{``0}},System.Func{``0,System.Threading.Tasks.Task{``1}},Jeebs.Option.Handler)~System.Threading.Tasks.Task{Jeebs.Option{``1}}")]
[assembly: SuppressMessage("Design", "RCS1224:Make method an extension method.", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.OptionExtensions.DoMatchAsync``2(System.Threading.Tasks.Task{Jeebs.Option{``0}},System.Func{``0,System.Threading.Tasks.Task{``1}},System.Func{Jeebs.IMsg,System.Threading.Tasks.Task{``1}})~System.Threading.Tasks.Task{``1}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.Option.CatchAsync``1(System.Func{System.Threading.Tasks.Task{Jeebs.Option{``0}}},Jeebs.Option.Handler)~System.Threading.Tasks.Task{Jeebs.Option{``0}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.Option`1.DoMapAsync``1(System.Func{`0,System.Threading.Tasks.Task{``0}},Jeebs.Option.Handler)~System.Threading.Tasks.Task{Jeebs.Option{``0}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.OptionExtensions.DoAuditAsync``1(System.Threading.Tasks.Task{Jeebs.Option{``0}},System.Func{Jeebs.Option{``0},System.Threading.Tasks.Task})~System.Threading.Tasks.Task{Jeebs.Option{``0}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.OptionExtensions.DoAuditSwitchAsync``1(System.Threading.Tasks.Task{Jeebs.Option{``0}},System.Func{``0,System.Threading.Tasks.Task},System.Func{Jeebs.IMsg,System.Threading.Tasks.Task})~System.Threading.Tasks.Task{Jeebs.Option{``0}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.OptionExtensions.DoBindAsync``2(System.Threading.Tasks.Task{Jeebs.Option{``0}},System.Func{``0,System.Threading.Tasks.Task{Jeebs.Option{``1}}},Jeebs.Option.Handler)~System.Threading.Tasks.Task{Jeebs.Option{``1}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.OptionExtensions.DoMapAsync``2(System.Threading.Tasks.Task{Jeebs.Option{``0}},System.Func{``0,System.Threading.Tasks.Task{``1}},Jeebs.Option.Handler)~System.Threading.Tasks.Task{Jeebs.Option{``1}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.OptionExtensions.DoMatchAsync``2(System.Threading.Tasks.Task{Jeebs.Option{``0}},System.Func{``0,System.Threading.Tasks.Task{``1}},System.Func{Jeebs.IMsg,System.Threading.Tasks.Task{``1}})~System.Threading.Tasks.Task{``1}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.OptionExtensions.UnwrapAsync``2(System.Threading.Tasks.Task{Jeebs.Option{``0}},System.Func{Jeebs.OptionExtensions.FluentUnwrapAsync{``0},Jeebs.Option{``1}})~System.Threading.Tasks.Task{Jeebs.Option{``1}}")]
