// Jeebs Test Applications
// Copyright (c) bcg|design - licensed under https://mit.bcgdesign.com/2013

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:AppConsoleWordPress.Program.ApplyContentFilters``1(Jeebs.IOk{``0,Jeebs.WordPress.IWpDb})~System.Threading.Tasks.Task{Jeebs.IR{System.Collections.Generic.List{AppConsoleWordPress.PostModelWithContent},Jeebs.WordPress.IWpDb}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:AppConsoleWordPress.Program.FetchCustomFields``1(Jeebs.IOk{``0,Jeebs.WordPress.IWpDb})~System.Threading.Tasks.Task{Jeebs.IR{System.Collections.Generic.List{AppConsoleWordPress.SermonModelWithCustomFields},Jeebs.WordPress.IWpDb}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:AppConsoleWordPress.Program.FetchMeta``1(Jeebs.IOk{``0,Jeebs.WordPress.IWpDb})~System.Threading.Tasks.Task{Jeebs.IR{System.Collections.Generic.List{AppConsoleWordPress.PostModel},Jeebs.WordPress.IWpDb}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:AppConsoleWordPress.Program.FetchTaxonomies``1(Jeebs.IOk{``0,Jeebs.WordPress.IWpDb})~System.Threading.Tasks.Task{Jeebs.IR{System.Collections.Generic.List{AppConsoleWordPress.SermonModelWithTaxonomies},Jeebs.WordPress.IWpDb}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:AppConsoleWordPress.Program.InsertOptionAsync(Jeebs.IOk,Jeebs.WordPress.IWpDb)~System.Threading.Tasks.Task{Jeebs.IR{AppConsoleWordPress.Bcg.Entities.Option}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:AppConsoleWordPress.Program.Main(System.String[])~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:AppConsoleWordPress.Program.SearchSermonsAsync(Jeebs.IOk{System.Boolean,Jeebs.WordPress.IWpDb},System.String,System.Action{Jeebs.WordPress.QueryPosts.Options})~System.Threading.Tasks.Task{Jeebs.IR{System.Collections.Generic.List{AppConsoleWordPress.SermonModel},Jeebs.WordPress.IWpDb}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:AppConsoleWordPress.Program.TermsAsync(Jeebs.IOk,System.String,Jeebs.WordPress.IWpDb)~System.Threading.Tasks.Task{Jeebs.IR{System.Int32}}")]
