// Jeebs Test Applications
// Copyright (c) bcg|design - licensed under https://mit.bcgdesign.com/2013

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:AppConsoleWordPress.Program.Main(System.String[])~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:AppConsoleWordPress.Program.TermsAsync(System.String,Jeebs.WordPress.IWpDb)~System.Threading.Tasks.Task{Jeebs.Option{System.Int32}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:AppConsoleWordPress.Program.ApplyContentFilters(Jeebs.WordPress.IWpDb)~System.Threading.Tasks.Task{Jeebs.Option{System.Collections.Generic.List{AppConsoleWordPress.PostModelWithContent}}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:AppConsoleWordPress.Program.FetchCustomFields(Jeebs.WordPress.IWpDb)~System.Threading.Tasks.Task{Jeebs.Option{System.Collections.Generic.List{AppConsoleWordPress.SermonModelWithCustomFields}}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:AppConsoleWordPress.Program.FetchMeta(Jeebs.WordPress.IWpDb)~System.Threading.Tasks.Task{Jeebs.Option{System.Collections.Generic.List{AppConsoleWordPress.PostModel}}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:AppConsoleWordPress.Program.FetchTaxonomies(Jeebs.WordPress.IWpDb)~System.Threading.Tasks.Task{Jeebs.Option{System.Collections.Generic.List{AppConsoleWordPress.SermonModelWithTaxonomies}}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:AppConsoleWordPress.Program.InsertOptionAsync(Jeebs.WordPress.IWpDb)~System.Threading.Tasks.Task{Jeebs.Option{AppConsoleWordPress.Bcg.Entities.Option}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:AppConsoleWordPress.Program.SearchSermonsAsync(Jeebs.WordPress.IWpDb,System.String,System.Action{Jeebs.WordPress.QueryPosts.Options})~System.Threading.Tasks.Task{Jeebs.Option{System.Collections.Generic.List{AppConsoleWordPress.SermonModel}}}")]
