<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Jeebs.Data.Testing</RootNamespace>
    <Configurations>Debug;Release;Test</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Jeebs.Data.Testing\Jeebs.Data.Testing.csproj" />
  </ItemGroup>
</Project>
