<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Configurations>Debug;Release;Test</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Rqlite" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Jeebs.Data\Jeebs.Data.csproj" />
  </ItemGroup>
</Project>
