<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Jeebs.Cryptography</RootNamespace>
    <Configurations>Debug;Release;Test</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Sodium.Core" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Jeebs.Cryptography\Jeebs.Cryptography.csproj" />
    <ProjectReference Include="..\..\src\Jeebs\Jeebs.csproj" />
  </ItemGroup>
</Project>
