// Jeebs Rapid Application Development
// Copyright (c) bcg|design - licensed under https://mit.bcgdesign.com/2013

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.WordPress.AttachmentCustomField.HydrateAsync(Jeebs.WordPress.IWpDb,Jeebs.Data.IUnitOfWork,Jeebs.WordPress.MetaDictionary)~System.Threading.Tasks.Task{Jeebs.Option{System.Boolean}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.WordPress.QueryWrapper.AddCustomFieldsAsync``2(``0)~System.Threading.Tasks.Task{Jeebs.Option{``0}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.WordPress.QueryWrapper.AddMetaAsync``2(``0)~System.Threading.Tasks.Task{Jeebs.Option{``0}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.WordPress.QueryWrapper.AddTaxonomiesAsync``2(``0)~System.Threading.Tasks.Task{Jeebs.Option{``0}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.WordPress.QueryWrapper.GetAttachedFilePathAsync(System.Int64,System.String)~System.Threading.Tasks.Task{Jeebs.Option{System.String}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.WordPress.QueryWrapper.GetAttachedFiles``1(System.Collections.Generic.List{System.Int64},System.String)~System.Threading.Tasks.Task{Jeebs.Option{System.Collections.Generic.List{``0}}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.WordPress.QueryWrapper.Process``2(``0,Jeebs.WordPress.ContentFilter[])~System.Threading.Tasks.Task{Jeebs.Option{``0}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.WordPress.QueryWrapper.QueryPostsAsync``1(System.Action{Jeebs.WordPress.QueryPosts.Options},Jeebs.WordPress.ContentFilter[])~System.Threading.Tasks.Task{Jeebs.Option{System.Collections.Generic.List{``0}}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.WordPress.QueryWrapper.QueryPostsAsync``1(System.Int64,System.Action{Jeebs.WordPress.QueryPosts.Options},Jeebs.WordPress.ContentFilter[])~System.Threading.Tasks.Task{Jeebs.Option{Jeebs.PagedList{``0}}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.WordPress.QueryWrapper.QueryPostsMetaAsync``1(System.Action{Jeebs.WordPress.QueryPostsMeta.Options})~System.Threading.Tasks.Task{Jeebs.Option{System.Collections.Generic.List{``0}}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.WordPress.QueryWrapper.QueryPostsPreviousAndNextAsync(System.Int64,System.Action{Jeebs.WordPress.QueryPosts.Options})~System.Threading.Tasks.Task{Jeebs.Option{System.ValueTuple{System.Nullable{System.Int64},System.Nullable{System.Int64}}}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.WordPress.QueryWrapper.QueryTaxonomyAsync``1(System.Action{Jeebs.WordPress.QueryTaxonomy.Options})~System.Threading.Tasks.Task{Jeebs.Option{System.Collections.Generic.List{``0}}}")]
[assembly: SuppressMessage("Design", "RCS1090:Add call to 'ConfigureAwait' (or vice versa).", Justification = "<Pending>", Scope = "member", Target = "~M:Jeebs.WordPress.TermCustomField.HydrateAsync(Jeebs.WordPress.IWpDb,Jeebs.Data.IUnitOfWork,Jeebs.WordPress.MetaDictionary)~System.Threading.Tasks.Task{Jeebs.Option{System.Boolean}}")]
